install.packages("MASS")
library(MASS)
attach(Boston)
?Boston
head(Boston, 10)
dim(Boston)
names(Boston)
str(Boston)
nrow(Boston)
ncol(Boston)
summary(Boston)
summary(Boston$crim)

library(ISLR)
data(Auto)
head(Auto)
names(Auto)
summary(Auto)
summary(Auto$mpg)
fivenum(Auto$mpg)
boxplot(Auto$mpg)
hist(Auto$mpg)
summary(Auto$horsepower)
summary(Auto$weight)
fivenum(Auto$weight)
boxplot(Auto$weight)
mean(Auto$weight)
median(Auto$weight)

data1 <- read.csv(file.choose(), header = TRUE)
summary(data1)
summary(data1$EPI)
boxplot(data1$EPI)
fivenum(data1$EPI, na.rm = TRUE)
hist(data1$EPI)